# Directory
[directory]
style = "blue"
truncation_length = 2
truncation_symbol = "â€¦/" 
read_only = " ğŸ”’"

# Prompt
[sudo]
format = "ğŸ‘® [$user]($style)[$symbol]($style) "
style = "red"
symbol = "#"

[username]
show_always = true
format = "ğŸ¦ˆ [$user]($style)[$symbol]($style) "
style_root = "red bold"
style_user = "green bold"

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

# Git
[git_branch]
format = "ğŸ˜º [$branch]($style) "
style = "bold green"

[git_status]
conflicted = "ğŸš©"
ahead = "ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = ""
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ï¸"

# Duration
[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# Development
[aws]
format = "via [$symbol$profile]($style) "
style = "dimmed bright-yellow"
symbol = "â˜ï¸ "

[gcloud]
format = "via [$symbol$account]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ’¨ "

[conda]
format = "via [$symbol$environment]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ‰ "

[python]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ "

[rust]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ¦€ "

[swift]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ•Šï¸ "

[dotnet]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ”§ "

[nodejs]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ‘½ "

[ruby]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ’ "

[java]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "â˜• "

[gradle]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ˜ "

[c]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ‘® "
detect_extensions = ["c", "h", "cpp"]

[cmake]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ› ï¸ "

[golang]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ¹ "

[bun]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ¥ "

[helm]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "â›‘ï¸ "

[kubernetes]
format = "via [$symbol$context]($style) "
style = "dimmed bright-yellow"
symbol = "â˜¸ï¸ "

[docker_context]
format = "via [$symbol$context]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ³ "

[terraform]
format = "via [$symbol$workspace]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸŒ "

[deno]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ¦• "

[elixir]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "ğŸ’§ "

[vagrant]
format = "via [$symbol$version]($style) "
style = "dimmed bright-yellow"
symbol = "âœˆï¸ "

